from __future__ import annotations

import json
from pathlib import Path

from .atomic_io import write_text_atomic
from .claude_bridge import run_claude_bridge
from .claude_statusline import (
    STATUSLINE_SCRIPT_NAME,
    inspect_claude_statusline,
    install_claude_statusline,
    statusline_destination,
    statusline_source,
)
from .paths import AgentbotPaths
from .skills_sources import load_skills_sources
from .workspace_render import (
    RenderAction,
    build_review_template_action,
    is_review_template_path,
)

GENERATED_AGENTS_HEADER = "<!-- Generated by Agentbot. Edit canonical AGENTS.md files instead. -->"


def merge_instruction_text(global_agents: Path, repo_agents: Path | None) -> str:
    parts = [GENERATED_AGENTS_HEADER, ""]
    parts.append(global_agents.read_text(encoding="utf-8").rstrip())
    repo_overlay = _read_repo_overlay(repo_agents)
    if repo_overlay:
        parts.extend(["", repo_overlay])
    return "\n".join(parts).rstrip() + "\n"


def render_global_outputs(paths: AgentbotPaths) -> None:
    """Render global AGENTS.md outputs and Codex skill symlinks.

    MCP writing from catalog is retired; `agentbot mcp` owns MCP now.
    """
    merged = merge_instruction_text(paths.global_agents, None)

    paths.codex_home.mkdir(parents=True, exist_ok=True)
    _render_global_output(paths.codex_home / "AGENTS.md", _codex_instruction_text(paths, merged))
    _sync_codex_skills(paths)

    paths.claude_home.mkdir(parents=True, exist_ok=True)
    # Claude Code reads CLAUDE.md, not AGENTS.md, at the user scope.
    _render_global_output(paths.claude_home / "CLAUDE.md", merged)
    install_claude_statusline(paths)
    run_claude_bridge(paths)


def plan_global_resync_actions(paths: AgentbotPaths) -> tuple[RenderAction, ...]:
    """Preview managed global home outputs (Codex/Claude AGENTS + statusline)."""
    if not paths.global_agents.is_file():
        return (
            RenderAction(
                "global/AGENTS.md",
                "conflict",
                None,
                f"missing global baseline: {paths.global_agents}",
            ),
        )

    desired = merge_instruction_text(paths.global_agents, None)
    codex_desired = _codex_instruction_text(paths, desired)
    actions: list[RenderAction] = [
        _plan_global_instruction_action(
            _display_managed_path(paths, paths.codex_home / "AGENTS.md"),
            paths.codex_home / "AGENTS.md",
            codex_desired,
        ),
        _plan_global_instruction_action(
            _display_managed_path(paths, paths.claude_home / "CLAUDE.md"),
            paths.claude_home / "CLAUDE.md",
            desired,
        ),
        _plan_statusline_action(paths),
    ]
    return tuple(actions)


def _codex_instruction_text(paths: AgentbotPaths, base: str) -> str:
    boost_awareness = paths.codex_home / "BOOST.md"
    if not boost_awareness.is_file() or boost_awareness.is_symlink():
        return base
    return f"{base.rstrip()}\n\n@BOOST.md\n"


def resync_global_outputs(paths: AgentbotPaths, *, apply: bool) -> tuple[RenderAction, ...]:
    """Preview or refresh managed global Codex/Claude outputs and statusline."""
    planned = plan_global_resync_actions(paths)
    if not apply:
        return planned
    if any(
        action.kind == "conflict" and action.relative_path == "global/AGENTS.md"
        for action in planned
    ):
        return planned
    render_global_outputs(paths)
    applied: list[RenderAction] = []
    for action in planned:
        if action.kind in {"create", "update"}:
            applied.append(
                RenderAction(
                    action.relative_path,
                    action.kind,
                    None,
                    action.detail.replace("would ", "", 1)
                    if action.detail.startswith("would ")
                    else action.detail,
                )
            )
        else:
            applied.append(action)
    return tuple(applied)


def _display_managed_path(paths: AgentbotPaths, path: Path) -> str:
    for home, prefix in (
        (paths.codex_home, "~/.codex"),
        (paths.claude_home, "~/.claude"),
    ):
        try:
            relative = path.resolve().relative_to(home.resolve())
            return f"{prefix}/{relative.as_posix()}"
        except ValueError:
            continue
    return _display_home_path(path)


def _display_home_path(path: Path) -> str:
    home = Path.home()
    try:
        return f"~/{path.resolve().relative_to(home).as_posix()}"
    except ValueError:
        return str(path)


def _plan_global_instruction_action(label: str, destination: Path, desired: str) -> RenderAction:
    existing = destination.read_text(encoding="utf-8") if destination.is_file() else None
    if existing is None:
        return RenderAction(label, "create", desired, f"would create managed {label}")
    if GENERATED_AGENTS_HEADER in existing:
        if existing == desired:
            return RenderAction(label, "unchanged", None, f"managed {label} is current")
        return RenderAction(label, "update", desired, f"would refresh managed {label}")
    return RenderAction(
        label,
        "unchanged",
        None,
        f"preserving user-owned {label}; review template may be refreshed on apply",
    )


def _plan_statusline_action(paths: AgentbotPaths) -> RenderAction:
    label = _display_managed_path(paths, statusline_destination(paths))
    source = statusline_source(paths)
    state = inspect_claude_statusline(paths)
    if not state.source_exists:
        return RenderAction(
            label,
            "conflict",
            None,
            f"missing managed statusline source: {source}",
        )
    if not state.installed:
        return RenderAction(label, "create", None, f"would install {STATUSLINE_SCRIPT_NAME}")
    if state.managed and not state.in_sync:
        return RenderAction(label, "update", None, f"would refresh {STATUSLINE_SCRIPT_NAME}")
    if not state.managed:
        return RenderAction(
            label, "unchanged", None, f"preserving user-owned {STATUSLINE_SCRIPT_NAME}"
        )
    if not state.settings_wired:
        return RenderAction(
            label,
            "update",
            None,
            f"would wire statusLine for {STATUSLINE_SCRIPT_NAME}",
        )
    detail = f"managed {STATUSLINE_SCRIPT_NAME} is current"
    if not state.jq_available:
        detail += " (jq missing)"
    return RenderAction(label, "unchanged", None, detail)


def _render_global_output(destination: Path, desired: str) -> None:
    _validate_global_output(destination)
    existing = destination.read_text(encoding="utf-8") if destination.is_file() else None
    review_files = _read_review_templates(destination)

    if existing is None or GENERATED_AGENTS_HEADER in existing:
        if existing != desired:
            write_text_atomic(destination, desired)
    else:
        action = build_review_template_action(str(destination), desired, review_files)
        _apply_review_action(action)
        return

    if review_files:
        action = build_review_template_action(str(destination), desired, review_files)
        _apply_review_action(action)


def _validate_global_output(destination: Path) -> None:
    if destination.is_symlink():
        raise ValueError(f"global output is a symlink: {destination}")
    if destination.exists() and not destination.is_file():
        raise ValueError(f"global output is not a regular file: {destination}")


def _read_review_templates(destination: Path) -> dict[str, str]:
    if not destination.parent.is_dir():
        return {}

    existing: dict[str, str] = {}
    for candidate in sorted(destination.parent.iterdir()):
        if not is_review_template_path(destination, candidate):
            continue
        if candidate.is_symlink():
            raise ValueError(f"global output is a symlink: {candidate}")
        if not candidate.is_file():
            raise ValueError(f"global output is not a regular file: {candidate}")
        existing[str(candidate)] = candidate.read_text(encoding="utf-8")
    return existing


def _apply_review_action(action: RenderAction) -> None:
    if action.kind not in {"create", "update"}:
        return
    destination = Path(action.relative_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    write_text_atomic(destination, action.content or "")


def _project_skills_lock(paths: AgentbotPaths) -> Path:
    return paths.root / "skills-lock.json"


def _skill_names_from_lock(lock_file: Path) -> list[str] | None:
    """Return lock skill names, or None when an existing lock is malformed."""
    if not lock_file.exists():
        return []

    try:
        data = json.loads(lock_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(data, dict):
        return None
    skills = data.get("skills")
    if isinstance(skills, dict):
        return sorted(skills.keys())

    sources = data.get("sources")
    if isinstance(sources, list):
        names: list[str] = []
        for item in sources:
            if isinstance(item, dict) and "name" in item:
                names.append(str(item["name"]))
            elif isinstance(item, str):
                names.append(item)
        return sorted(names)

    return []


def managed_skill_names(paths: AgentbotPaths) -> list[str]:
    lock_names = _skill_names_from_lock(_project_skills_lock(paths))
    # The project lock is only a stub for global installs; a malformed stub
    # must not prevent a valid authoritative global lock from being used.
    if lock_names is None:
        lock_names = []
    if not lock_names:
        lock_names = _manifest_managed_global_skill_names(paths)
    return lock_names or []


def _manifest_managed_global_skill_names(paths: AgentbotPaths) -> list[str] | None:
    try:
        lock = json.loads(paths.global_skill_lock.read_text(encoding="utf-8"))
        config = load_skills_sources(paths.skills_sources_file)
    except (OSError, ValueError):
        return _skill_names_from_lock(paths.global_skill_lock)
    if not isinstance(lock, dict) or not isinstance(lock.get("skills"), dict):
        return _skill_names_from_lock(paths.global_skill_lock)

    active_sources = {source.repo: source for source in config.active_sources()}
    names: list[str] = []
    for name, entry in lock["skills"].items():
        if not isinstance(entry, dict):
            continue
        source = active_sources.get(entry.get("source"))
        if source is None:
            continue
        if source.skills == ["*"] or name in source.skills:
            names.append(str(name))
    return sorted(names)


def installed_skill_dirs(paths: AgentbotPaths) -> list[Path]:
    """Return every valid local skill directory, regardless of lock provenance."""
    agents_home = paths.agents_skills_home
    if not agents_home.exists():
        return []

    return [
        skill_dir.resolve()
        for skill_dir in sorted(agents_home.iterdir())
        if skill_dir.is_dir() and (skill_dir / "SKILL.md").exists()
    ]


def _sync_codex_skills(paths: AgentbotPaths) -> None:
    skills_home = paths.codex_home / "skills"
    skills_home.mkdir(parents=True, exist_ok=True)

    wanted = {skill_dir.name for skill_dir in installed_skill_dirs(paths)}
    agents_home = paths.agents_skills_home

    for skill_name in sorted(wanted):
        source = agents_home / skill_name
        if not (source / "SKILL.md").exists():
            continue
        target = skills_home / skill_name
        if target.is_symlink() or target.exists():
            if target.resolve() == source.resolve():
                continue
            # A different path belongs to the user or another installer. Never
            # replace it merely because this source is currently lock-managed.
            continue
        target.symlink_to(source.resolve())


def _read_repo_overlay(repo_agents: Path | None) -> str | None:
    if repo_agents is None or not repo_agents.exists():
        return None
    content = repo_agents.read_text(encoding="utf-8").rstrip()
    return content or None
