from __future__ import annotations

import hashlib
import os
import re
import tempfile
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

MANAGED_BEGIN = "<!-- BEGIN AGENTBOT MANAGED BASELINE -->"
MANAGED_END = "<!-- END AGENTBOT MANAGED BASELINE -->"
GENERATED_HEADER = "<!-- Generated by Agentbot. Edit AGENTS.md, not this file. -->"
REVIEW_TEMPLATE_MARKER = "<!-- Agentbot review template: sha256="
REVIEW_TEMPLATE_PATTERN = re.compile(
    r"\A<!-- Agentbot review template: sha256=([0-9a-f]{64}) -->\r?\n"
)
PROJECT_HEADING = re.compile(r"(?m)^## Project[ \t]*(?:\n|$)")

OUTPUT_PATHS = {
    "agents": "AGENTS.md",
    "claude": "CLAUDE.md",
    "cursor": ".cursor/rules/agentbot-policy.mdc",
}
WORKSPACE_TARGETS = frozenset(OUTPUT_PATHS)
# Outputs from targets Agentbot no longer supports. Nothing renders these, but
# an existing file still carries the managed markers, so the orphan check keeps
# reporting it -- otherwise dropping a target would make its leftover file
# invisible and permanently stale.
RETIRED_OUTPUT_PATHS = {
    "copilot": ".github/copilot-instructions.md",
}
LEGACY_CLAUDE_CONTENT = (
    "IMPORTANT: Read and follow all instructions in AGENTS.md before starting any task.\n\n"
    "@AGENTS.md\n"
)


@dataclass(frozen=True)
class RenderAction:
    relative_path: str
    kind: Literal["create", "update", "unchanged", "conflict"]
    content: str | None
    detail: str


@dataclass(frozen=True)
class WorkspaceRenderPlan:
    actions: tuple[RenderAction, ...]
    policy_mode: Literal["managed", "custom"]

    def action_for(self, relative_path: str) -> RenderAction:
        for action in self.actions:
            if action.relative_path == relative_path:
                return action
        raise KeyError(relative_path)

    def paths(self) -> tuple[str, ...]:
        return tuple(action.relative_path for action in self.actions)


def build_workspace_render_plan(
    base_template: str,
    existing_files: Mapping[str, str],
    selected_targets: Sequence[str],
) -> WorkspaceRenderPlan:
    _validate_existing_paths(existing_files)
    targets = _normalize_targets(selected_targets)
    # Validates the base template up front: this raises when the "## Project"
    # heading is missing, before any output is planned. The split itself is
    # redone per target below.
    split_base_template(base_template)

    existing_agents = existing_files.get("AGENTS.md")
    policy_mode: Literal["managed", "custom"]
    malformed_agents_detail: str | None = None
    try:
        resolved_agents, policy_mode = resolve_agents_policy(
            base_template,
            existing_agents,
        )
    except ValueError as error:
        resolved_agents = existing_agents or ""
        policy_mode = "custom"
        malformed_agents_detail = str(error)

    actions: list[RenderAction] = []
    agents_path = OUTPUT_PATHS["agents"]
    if malformed_agents_detail is not None:
        actions.append(
            RenderAction(
                relative_path=agents_path,
                kind="unchanged",
                content=existing_agents,
                detail=f"preserve AGENTS.md: {malformed_agents_detail}",
            )
        )
        actions.append(
            build_review_template_action(
                agents_path,
                base_template,
                existing_files,
            )
        )
    else:
        actions.append(
            _content_action(
                agents_path,
                existing_agents,
                resolved_agents,
                create_detail="create managed AGENTS.md",
                update_detail="refresh managed AGENTS.md baseline",
                unchanged_detail="managed AGENTS.md is current",
                custom_detail="preserve custom AGENTS.md",
                custom=(policy_mode == "custom"),
            )
        )
        if policy_mode == "custom" or _has_review_template(agents_path, existing_files):
            actions.append(
                build_review_template_action(
                    agents_path,
                    base_template,
                    existing_files,
                )
            )

    renderers = {
        "claude": lambda: render_claude(),
        "cursor": lambda: render_cursor(),
    }
    for target in ("claude", "cursor"):
        if target not in targets:
            continue
        relative_path = OUTPUT_PATHS[target]
        desired = renderers[target]()
        existing = existing_files.get(relative_path)
        actions.append(
            _compatibility_action(
                relative_path,
                existing,
                desired,
                target=target,
            )
        )
        if (
            existing is not None and not _is_agentbot_owned_compatibility(relative_path, existing)
        ) or _has_review_template(relative_path, existing_files):
            actions.append(
                build_review_template_action(
                    relative_path,
                    desired,
                    existing_files,
                )
            )

    return WorkspaceRenderPlan(actions=tuple(actions), policy_mode=policy_mode)


def split_base_template(template: str) -> tuple[str, str]:
    match = PROJECT_HEADING.search(template)
    if match is None:
        raise ValueError("base AGENTS.md must contain a ## Project heading")
    prefix = template[: match.start()]
    project = template[match.start() :].lstrip("\n")
    return prefix, project


def render_managed_agents(base_prefix: str, project_section: str) -> str:
    return (
        f"{MANAGED_BEGIN}\n\n"
        f"{base_prefix.rstrip()}\n\n"
        f"{MANAGED_END}\n\n"
        f"{project_section.rstrip()}\n"
    )


def review_template_path(relative_path: str | Path, index: int = 0) -> str | Path:
    if index < 0:
        raise ValueError("review template index must not be negative")
    path = Path(relative_path)
    suffix = "_temp" if index == 0 else f"_temp_{index}"
    candidate = path.with_name(f"{path.stem}{suffix}{path.suffix}")
    return str(candidate) if isinstance(relative_path, str) else candidate


def is_review_template_path(relative_path: str | Path, candidate: str | Path) -> bool:
    source = Path(relative_path)
    target = Path(candidate)
    if source.parent != target.parent or source.suffix != target.suffix:
        return False
    pattern = rf"{re.escape(source.stem)}_temp(?:_\d+)?{re.escape(source.suffix)}"
    return re.fullmatch(pattern, target.name) is not None


def stamp_review_template(content: str) -> str:
    digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
    return f"{REVIEW_TEMPLATE_MARKER}{digest} -->\n{content}"


def review_template_body(content: str) -> str:
    match = REVIEW_TEMPLATE_PATTERN.match(content)
    return content[match.end() :] if match is not None else content


def build_review_template_action(
    relative_path: str,
    desired: str,
    existing_files: Mapping[str, str],
) -> RenderAction:
    desired_digest = hashlib.sha256(desired.encode("utf-8")).hexdigest()
    index = 0
    while True:
        candidate = str(review_template_path(relative_path, index))
        existing = existing_files.get(candidate)
        if existing is None:
            return RenderAction(
                candidate,
                "create",
                stamp_review_template(desired),
                f"create {candidate} review template; preserve {relative_path}",
            )

        match = REVIEW_TEMPLATE_PATTERN.match(existing)
        if match is None:
            if existing == desired:
                return RenderAction(
                    candidate,
                    "update",
                    stamp_review_template(desired),
                    f"stamp {candidate} review template",
                )
            state = "edited-stale"
        else:
            recorded_digest = match.group(1)
            body = existing[match.end() :]
            body_digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
            if body_digest == recorded_digest:
                stamped = stamp_review_template(desired)
                return RenderAction(
                    candidate,
                    "unchanged" if existing == stamped else "update",
                    stamped,
                    f"refresh {candidate} review template",
                )
            state = "edited-current" if recorded_digest == desired_digest else "edited-stale"

        if state == "edited-current":
            return RenderAction(
                candidate,
                "unchanged",
                existing,
                f"preserve edited {candidate} review template",
            )
        index += 1


def _has_review_template(relative_path: str, existing_files: Mapping[str, str]) -> bool:
    return any(is_review_template_path(relative_path, candidate) for candidate in existing_files)


def resolve_agents_policy(
    base_template: str,
    existing_content: str | None,
) -> tuple[str, Literal["managed", "custom"]]:
    base_prefix, base_project = split_base_template(base_template)
    if existing_content is None:
        return render_managed_agents(base_prefix, base_project), "managed"

    existing_content = review_template_body(existing_content)

    has_marker = MANAGED_BEGIN in existing_content or MANAGED_END in existing_content
    if has_marker:
        if existing_content.count(MANAGED_BEGIN) != 1 or existing_content.count(MANAGED_END) != 1:
            raise ValueError("AGENTS.md has an invalid Agentbot marker pair")
        begin = existing_content.index(MANAGED_BEGIN)
        end = existing_content.index(MANAGED_END)
        if begin > end:
            raise ValueError("AGENTS.md has an out-of-order Agentbot marker pair")
        suffix_start = end + len(MANAGED_END)
        suffix = existing_content[suffix_start:]
        if PROJECT_HEADING.search(suffix) is None:
            raise ValueError("managed AGENTS.md must contain a ## Project section after markers")
        replacement = f"{MANAGED_BEGIN}\n\n{base_prefix.rstrip()}\n\n{MANAGED_END}"
        return (
            existing_content[:begin] + replacement + existing_content[suffix_start:],
            "managed",
        )

    base_match = PROJECT_HEADING.search(base_template)
    existing_match = PROJECT_HEADING.search(existing_content)
    if (
        base_match is not None
        and existing_match is not None
        and existing_content[: existing_match.start()] == base_template[: base_match.start()]
    ):
        project_section = existing_content[existing_match.start() :].lstrip("\n")
        return render_managed_agents(base_prefix, project_section), "managed"

    return existing_content, "custom"


def render_claude() -> str:
    return (
        f"{GENERATED_HEADER}\n\n"
        "IMPORTANT: Read and follow all instructions in AGENTS.md before starting any task.\n\n"
        "@AGENTS.md\n"
    )


def render_cursor() -> str:
    """A pointer, not a copy.

    Cursor reads `.cursor/rules/`, `AGENTS.md`, and `CLAUDE.md` and applies all
    of them. Rendering the full policy here meant Cursor loaded it twice --
    once from AGENTS.md and again from this file -- for every request. Cursor
    has no import syntax, so this states the reference in prose instead, the
    same shape CLAUDE.md already uses.

    Cursor-only behavior, if any is ever needed, belongs here. Portable policy
    does not.
    """
    return (
        "---\n"
        "description: Agentbot-managed repository instructions\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"{GENERATED_HEADER}\n\n"
        "IMPORTANT: Read and follow all instructions in AGENTS.md at the "
        "repository root before starting any task. It is the canonical policy "
        "for this repository; this file adds nothing to it.\n"
    )


def apply_workspace_render_plan(
    root: Path,
    plan: WorkspaceRenderPlan,
) -> tuple[RenderAction, ...]:
    conflicts = [action for action in plan.actions if action.kind == "conflict"]
    if conflicts:
        paths = ", ".join(action.relative_path for action in conflicts)
        raise ValueError(f"cannot apply workspace render plan with conflicts: {paths}")

    writes = [action for action in plan.actions if action.kind in {"create", "update"}]
    _validate_write_locations(root, writes)
    applied: list[RenderAction] = []
    for action in writes:
        destination = root / action.relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        fd, temporary_name = tempfile.mkstemp(
            prefix=f".{destination.name}.agentbot-",
            dir=destination.parent,
        )
        temporary = Path(temporary_name)
        try:
            os.fchmod(fd, 0o644)
            with os.fdopen(fd, "w", encoding="utf-8", newline="") as stream:
                stream.write(action.content or "")
                stream.flush()
                os.fsync(stream.fileno())
            os.replace(temporary, destination)
            applied.append(action)
        finally:
            if temporary.exists():
                temporary.unlink()

    return tuple(applied)


def _normalize_targets(selected_targets: Sequence[str]) -> tuple[str, ...]:
    targets: list[str] = []
    for target in selected_targets:
        normalized = "agents" if target == "codex" else target
        if normalized not in WORKSPACE_TARGETS:
            raise ValueError(f"unsupported workspace target: {target}")
        if normalized in targets:
            raise ValueError(f"duplicate workspace target: {normalized}")
        targets.append(normalized)
    if "agents" not in targets:
        targets.insert(0, "agents")
    return tuple(target for target in OUTPUT_PATHS if target in targets)


def _validate_existing_paths(existing_files: Mapping[str, str]) -> None:
    allowed = set(OUTPUT_PATHS.values())
    for path in existing_files:
        if path not in allowed and not any(
            is_review_template_path(output_path, path) for output_path in allowed
        ):
            raise ValueError(f"unsupported workspace target: {path}")


def _content_action(
    relative_path: str,
    existing: str | None,
    desired: str,
    *,
    create_detail: str,
    update_detail: str,
    unchanged_detail: str,
    custom_detail: str,
    custom: bool,
) -> RenderAction:
    if custom:
        return RenderAction(relative_path, "unchanged", existing, custom_detail)
    if existing is None:
        return RenderAction(relative_path, "create", desired, create_detail)
    if existing == desired:
        return RenderAction(relative_path, "unchanged", desired, unchanged_detail)
    return RenderAction(relative_path, "update", desired, update_detail)


def _compatibility_action(
    relative_path: str,
    existing: str | None,
    desired: str,
    *,
    target: str,
) -> RenderAction:
    if existing is None:
        return RenderAction(relative_path, "create", desired, f"create {target} output")
    if not _is_agentbot_owned_compatibility(relative_path, existing):
        return RenderAction(
            relative_path,
            "unchanged",
            existing,
            f"preserve unowned {target} file; review template is separate",
        )
    if existing == desired:
        return RenderAction(relative_path, "unchanged", desired, f"{target} output is current")
    return RenderAction(relative_path, "update", desired, f"refresh {target} output")


def _is_agentbot_owned_compatibility(relative_path: str, content: str) -> bool:
    if GENERATED_HEADER in content:
        return True
    return relative_path == OUTPUT_PATHS["claude"] and content == LEGACY_CLAUDE_CONTENT


def _validate_write_locations(root: Path, actions: Sequence[RenderAction]) -> None:
    root = root.resolve()
    if not root.is_dir():
        raise ValueError(f"workspace root is not a directory: {root}")
    for action in actions:
        destination = root / action.relative_path
        current = root
        for part in Path(action.relative_path).parts[:-1]:
            current /= part
            if current.exists() and (current.is_symlink() or not current.is_dir()):
                raise ValueError(f"workspace output parent is unsafe: {current}")
        if destination.is_symlink():
            raise ValueError(f"workspace output is a symlink: {destination}")
